/**
 * Sound, synthesised rather than sampled.
 *
 * Every note here is generated by the Web Audio API. That is a deliberate
 * choice for this platform: audio files would be the largest thing in the
 * bundle by far, they would each need a licence recorded in THIRD-PARTY.md,
 * and Playables caps the initial download at 30 MB. This module is a few
 * kilobytes of code and needs no network at all.
 *
 * Two rules the browser imposes, both of which shape the design:
 *
 *   1. An AudioContext cannot start before a user gesture. So nothing is
 *      created at import time; `unlock()` runs on the first tap.
 *   2. A paused game must stop its music. The platform's onPause/onResume are
 *      the only source of that: the Page Visibility API is forbidden by the
 *      certification requirements, so this module never asks the document
 *      whether it is visible. `pauseAudio`/`resumeAudio` are called from
 *      main.js, wired to the SDK.
 *
 * YouTube's own mute sits above everything the player chose here. When it is
 * on, no audio may be output at all, whatever the in-game switches say.
 */

let ctx = null;
let master = null;      // everything goes through here, so one gain mutes all
let musicBus = null;
let sfxBus = null;
let started = false;

const settings = { music: true, sfx: true };
// Set from ytgame.system.isAudioEnabled / onAudioEnabledChange. Not a player
// setting: it overrides both of them.
let platformAudio = true;
let paused = false;

const musicAudible = () => settings.music && platformAudio && !paused;
const sfxAudible = () => settings.sfx && platformAudio && !paused;

/** Create the graph. Safe to call repeatedly; only the first call builds it. */
function ensure() {
  if (ctx) return ctx;
  const AC = window.AudioContext || window.webkitAudioContext;
  if (!AC) return null;
  ctx = new AC();

  master = ctx.createGain();
  master.gain.value = 0.9;
  master.connect(ctx.destination);

  // Music sits well under the effects: it is background, not foreground.
  musicBus = ctx.createGain();
  musicBus.gain.value = musicAudible() ? 0.16 : 0;
  musicBus.connect(master);

  sfxBus = ctx.createGain();
  sfxBus.gain.value = sfxAudible() ? 0.5 : 0;
  sfxBus.connect(master);

  return ctx;
}

/**
 * Called from the first user gesture. Until this runs the context either does
 * not exist or is suspended, and every sound below is a no-op.
 */
export function unlock() {
  const c = ensure();
  if (!c) return;
  if (c.state === 'suspended') c.resume();
  if (musicAudible() && !started) startMusic();
}

/**
 * YouTube's mute. Silences both buses outright and stops the loop, so a muted
 * game is not merely inaudible — it is doing no audio work at all.
 */
export function setPlatformAudio(enabled) {
  platformAudio = enabled !== false;
  applyGains();
  if (musicAudible()) startMusic(); else stopMusic();
}

export function isPlatformAudioEnabled() { return platformAudio; }

/** The platform paused us. Everything stops; nothing about the player's
 *  settings changes, so resume puts back exactly what they had. */
export function pauseAudio() {
  paused = true;
  applyGains();
  stopMusic();
}

export function resumeAudio() {
  paused = false;
  applyGains();
  if (musicAudible()) startMusic();
}

function applyGains() {
  if (!ctx) return;
  ramp(musicBus.gain, musicAudible() ? 0.16 : 0, 0.25);
  ramp(sfxBus.gain, sfxAudible() ? 0.5 : 0, 0.15);
}

export function isMusicOn() { return settings.music; }
export function isSfxOn() { return settings.sfx; }

export function setMusic(on) {
  settings.music = Boolean(on);
  applyGains();
  if (musicAudible()) startMusic(); else stopMusic();
}

export function setSfx(on) {
  settings.sfx = Boolean(on);
  applyGains();
}

function ramp(param, to, secs) {
  const t = ctx.currentTime;
  param.cancelScheduledValues(t);
  param.setValueAtTime(param.value, t);
  param.linearRampToValueAtTime(to, t + secs);
}

// ---------------------------------------------------------------------------
// effects
// ---------------------------------------------------------------------------

/**
 * One shaped note. Everything else here is built from this.
 * Soft waveforms and a short attack — square waves and instant onsets are what
 * make synthesised game audio sound cheap.
 */
function tone(freq, {
  at = 0, dur = 0.16, type = 'sine', gain = 0.5, glide = 0, bus = sfxBus,
  attack = 0.012,
} = {}) {
  if (!ctx || !bus) return;
  const t0 = ctx.currentTime + at;
  const osc = ctx.createOscillator();
  const g = ctx.createGain();
  osc.type = type;
  osc.frequency.setValueAtTime(freq, t0);
  if (glide) osc.frequency.exponentialRampToValueAtTime(Math.max(1, freq * glide), t0 + dur);

  // A long attack is what separates a pad from a pluck: the chord swells in
  // rather than announcing itself, so it stays behind the effects.
  const rise = Math.min(attack, dur * 0.5);
  g.gain.setValueAtTime(0, t0);
  g.gain.linearRampToValueAtTime(gain, t0 + rise);
  g.gain.exponentialRampToValueAtTime(0.0001, t0 + dur);

  osc.connect(g); g.connect(bus);
  osc.start(t0);
  osc.stop(t0 + dur + 0.02);
}

/** Filtered noise, for anything that should sound like an event not a note. */
function noise({ at = 0, dur = 0.2, gain = 0.25, freq = 1200, q = 1, bus = sfxBus } = {}) {
  if (!ctx || !bus) return;
  const t0 = ctx.currentTime + at;
  const n = Math.floor(ctx.sampleRate * dur);
  const buf = ctx.createBuffer(1, n, ctx.sampleRate);
  const d = buf.getChannelData(0);
  for (let i = 0; i < n; i++) d[i] = (Math.random() * 2 - 1) * (1 - i / n);

  const src = ctx.createBufferSource();
  src.buffer = buf;
  const bp = ctx.createBiquadFilter();
  bp.type = 'bandpass'; bp.frequency.value = freq; bp.Q.value = q;
  const g = ctx.createGain();
  g.gain.setValueAtTime(gain, t0);
  g.gain.exponentialRampToValueAtTime(0.0001, t0 + dur);

  src.connect(bp); bp.connect(g); g.connect(bus);
  src.start(t0);
}

// C major pentatonic, the safe scale: no interval in it can clash with the
// music underneath, whatever order the player triggers things in.
const PENT = [261.63, 293.66, 329.63, 392.00, 440.00, 523.25, 587.33, 659.25, 783.99, 880.00];

const EFFECTS = {
  // A tile joins the word. Climbs the scale as the word gets longer, so a
  // long drag sounds like it is building to something.
  tap: (i = 0) => tone(PENT[Math.min(i, PENT.length - 1)], { dur: 0.12, type: 'triangle', gain: 0.42 }),

  // A target word lands: a rising third.
  good: () => { tone(523.25, { dur: 0.13, type: 'triangle', gain: 0.5 });
                tone(659.25, { at: 0.09, dur: 0.22, type: 'triangle', gain: 0.45 }); },

  // An extra word: the same idea, one note further, brighter.
  bonus: () => { tone(523.25, { dur: 0.1, type: 'triangle', gain: 0.42 });
                 tone(659.25, { at: 0.07, dur: 0.1, type: 'triangle', gain: 0.42 });
                 tone(783.99, { at: 0.14, dur: 0.3, type: 'triangle', gain: 0.4 }); },

  // Not a word. Deliberately soft and low: a rejection should not punish.
  bad: () => tone(180, { dur: 0.16, type: 'sine', gain: 0.3, glide: 0.72 }),

  coin: () => { tone(987.77, { dur: 0.07, type: 'triangle', gain: 0.34 });
                tone(1318.51, { at: 0.05, dur: 0.14, type: 'triangle', gain: 0.3 }); },

  // Soil and leaves, not a note.
  plant: () => noise({ dur: 0.26, freq: 620, q: 0.7, gain: 0.22 }),
  harvest: () => { noise({ dur: 0.16, freq: 1400, q: 0.8, gain: 0.2 });
                   tone(659.25, { at: 0.05, dur: 0.2, type: 'triangle', gain: 0.36 }); },

  buy: () => { tone(392, { dur: 0.1, type: 'triangle', gain: 0.4 });
               tone(587.33, { at: 0.08, dur: 0.24, type: 'triangle', gain: 0.38 }); },

  // Wings and alarm — the one sound allowed to be unpleasant.
  raid: () => { noise({ dur: 0.34, freq: 900, q: 0.5, gain: 0.26 });
                tone(233.08, { dur: 0.3, type: 'sawtooth', gain: 0.18, glide: 0.7 }); },

  // Round complete: a full pentatonic run.
  win: () => [523.25, 587.33, 659.25, 783.99, 1046.5].forEach((f, i) =>
    tone(f, { at: i * 0.085, dur: i === 4 ? 0.6 : 0.18, type: 'triangle', gain: 0.42 })),

  // The 247 fills. The biggest moment in the game gets the biggest sound.
  jackpot: () => [523.25, 659.25, 783.99, 1046.5, 1318.51, 1567.98].forEach((f, i) =>
    tone(f, { at: i * 0.1, dur: i === 5 ? 1.1 : 0.24, type: 'triangle', gain: 0.45 })),
};

/** Play one effect by name. Silent until `unlock()` has run. */
export function sfx(name, arg) {
  if (!sfxAudible() || !ctx || ctx.state !== 'running') return;
  EFFECTS[name]?.(arg);
}

// ---------------------------------------------------------------------------
// music
// ---------------------------------------------------------------------------
/**
 * The loop, written as game music rather than ambience.
 *
 * Two earlier versions did not work. The first picked random pentatonic notes
 * over a drone — never wrong, since nothing in a pentatonic scale can be, but
 * it never went anywhere. The second added real harmony but kept the long
 * swelling pads, which made it wallpaper: pleasant, and completely inert. What
 * a puzzle game wants is a pulse you can feel, so this has one.
 *
 * Per bar, at 108 BPM: a kick on 1 and 3, hats on the off-beats, a bass that
 * walks instead of holding, and a plucked lead playing eighth notes with rests
 * in them. The chords are I - vi - IV - V in C, the most cheerful four bars in
 * popular music, and the lead draws from C major pentatonic, which is
 * consonant with all four — so the rhythm can vary freely without ever
 * landing on a wrong note.
 */
let timer = null;
let bar = 0;

// Semitones from the root. Bass takes the chord's root; the pad is a light
// triad, held only about half a bar so it never turns back into a drone.
const PROGRESSION = [
  { name: 'C',  root: 0,  triad: [0, 4, 7] },
  { name: 'Am', root: -3, triad: [-3, 0, 4] },
  { name: 'F',  root: -7, triad: [-7, -3, 0] },
  { name: 'G',  root: -5, triad: [-5, -1, 2] },
];

/** Equal temperament, so a chord can be written as semitones not frequencies. */
const semi = (root, n) => root * Math.pow(2, n / 12);

// C major pentatonic across two octaves, as semitone offsets.
const LEAD = [0, 2, 4, 7, 9, 12, 14, 16, 19, 21];

// Eight eighth-notes per bar. 1 plays, 0 rests — the rests are the groove.
const RHYTHMS = [
  [1, 0, 1, 1, 0, 1, 0, 1],
  [1, 1, 0, 1, 0, 1, 1, 0],
  [1, 0, 1, 0, 1, 1, 0, 1],
  [1, 1, 0, 1, 1, 0, 1, 0],
];

// Where the lead sits in LEAD[] across the bar. Shapes, not random walks, so
// each bar is a phrase rather than a scatter of notes.
const SHAPES = [
  [3, 4, 5, 4, 6, 5, 4, 3],
  [5, 4, 3, 4, 5, 6, 7, 5],
  [4, 5, 7, 6, 5, 4, 3, 4],
  [7, 6, 5, 6, 4, 5, 3, 4],
];

let mood = { root: 261.63, bpm: 108, gain: 1, drums: true };

/** The sky sets the tempo and weight — night plays the same tune, softer. */
export function setMood(skyId) {
  mood = skyId === 'night'   ? { root: 220.00, bpm: 84,  gain: 0.7, drums: false }
       : skyId === 'monsoon' ? { root: 233.08, bpm: 92,  gain: 0.8, drums: true }
       : skyId === 'dusk'    ? { root: 246.94, bpm: 96,  gain: 0.85, drums: true }
       : skyId === 'dawn'    ? { root: 261.63, bpm: 100, gain: 0.9, drums: true }
       : skyId === 'mist'    ? { root: 246.94, bpm: 96,  gain: 0.8, drums: false }
       : { root: 261.63, bpm: 108, gain: 1, drums: true };
}

/** A soft kick: a pitch drop with a body, not a click. */
function kick(at) {
  tone(110, {
    at, dur: 0.22, type: 'sine', gain: 0.55 * mood.gain, glide: 0.36,
    bus: musicBus, attack: 0.004,
  });
}

/** A hat, quiet and high — the thing that makes a beat feel like a beat. */
function hat(at) {
  noise({ at, dur: 0.045, freq: 8000, q: 1.4, gain: 0.07 * mood.gain, bus: musicBus });
}

function startMusic() {
  if (!ctx || ctx.state !== 'running' || timer) return;
  started = true;

  const step = () => {
    if (!musicAudible()) return;
    const chord = PROGRESSION[bar % PROGRESSION.length];
    const beatSecs = 60 / mood.bpm;
    const barSecs = beatSecs * 4;
    const eighth = beatSecs / 2;
    const g = mood.gain;

    if (mood.drums) {
      kick(0);
      kick(beatSecs * 2);
      for (let i = 0; i < 8; i++) if (i % 2 === 1) hat(i * eighth);
    }

    // Bass walks: root, root, fifth, root-an-octave-up. Short and plucked,
    // so it drives the bar instead of sitting under it.
    const bassLine = [chord.root, chord.root, chord.root + 7, chord.root + 12];
    bassLine.forEach((n, i) => {
      tone(semi(mood.root, n) / 2, {
        at: i * beatSecs, dur: beatSecs * 0.62, type: 'triangle',
        gain: 0.34 * g, bus: musicBus, attack: 0.008,
      });
    });

    // A light triad on the off-beat of 1 and 3 — a stab, not a pad.
    for (const off of [eighth, beatSecs * 2 + eighth]) {
      for (const n of chord.triad) {
        tone(semi(mood.root, n), {
          at: off, dur: beatSecs * 0.4, type: 'sine',
          gain: 0.11 * g, bus: musicBus, attack: 0.01,
        });
      }
    }

    // The lead. Rhythm and shape are chosen per bar and paired independently,
    // so sixteen combinations come round in an order you cannot hum ahead.
    const rhythm = RHYTHMS[(bar + (bar >> 2)) % RHYTHMS.length];
    const shape = SHAPES[(bar >> 1) % SHAPES.length];
    for (let i = 0; i < 8; i++) {
      if (!rhythm[i]) continue;
      const n = LEAD[shape[i] % LEAD.length];
      tone(semi(mood.root, n), {
        at: i * eighth, dur: eighth * 1.7, type: 'triangle',
        gain: 0.2 * g, bus: musicBus, attack: 0.006,
      });
    }

    bar++;
    timer = setTimeout(step, barSecs * 1000);
  };
  step();
}

function stopMusic() {
  clearTimeout(timer);
  timer = null;
  started = false;
}
