/**
 * Build the level pool set from the generated dictionary.
 *
 *   node tools/dict.mjs && node tools/genpools.mjs
 *
 * Writes src/game/levelwords.js: the words levels draw their targets from,
 * with meanings, plus a pool for every wheel size from 4 to 8.
 *
 * Targets come from the commonest slice of the dictionary, because a target
 * you have never heard of is not a puzzle, it is a wall. Rarer words still
 * count as bonus finds — that is what the full dictionary is for.
 */
import fs from 'node:fs';
import { letters, letterIndex, buildableFrom, toBag } from '../src/tamil/letters.js';

const SIZES = [6, 7, 8, 9, 10];  // wheel sizes the game asks for
const PER_SIZE = 320;     // pools kept per wheel size
const MIN_WORDS = 4;      // a level worth playing needs a few words in it

const targets = JSON.parse(fs.readFileSync('public/dict/ta-targets.json', 'utf8'));

// Targets come pre-curated by tools/dict.mjs: concrete nouns and adjectives
// with short plain meanings that a hint can actually say out loud. Everything
// else in the dictionary stays valid as a bonus find, it just never becomes
// homework.
const pool = targets
  .map((e) => ({ ...e, ls: letters(e.w) }))
  .filter((e) => e.ls.length >= 2 && e.ls.length <= 6
    && e.ls.every((l) => letterIndex(l) >= 0));

console.log(`target vocabulary: ${pool.length} curated words`);

// Subset testing by bitmask. Scanning the whole vocabulary for every candidate
// pool is ~10^9 comparisons; a mask rejects most words in one operation.
const letterBit = new Map();
const maskOf = (ls) => {
  let m = 0n;
  for (const l of ls) {
    if (!letterBit.has(l)) letterBit.set(l, BigInt(letterBit.size));
    m |= 1n << letterBit.get(l);
  }
  return m;
};
for (const e of pool) e.mask = maskOf(e.ls);

const union = (a, b) => {
  const o = new Map(a);
  for (const [l, n] of b) o.set(l, Math.max(o.get(l) || 0, n));
  return o;
};
const size = (b) => [...b.values()].reduce((x, y) => x + y, 0);
const flat = (b) => [...b].flatMap(([l, n]) => Array(n).fill(l));

const found = new Map();
for (let i = 0; i < pool.length; i++) {
  for (let j = i + 1; j < pool.length; j++) {
    const bag = union(toBag(pool[i].ls), toBag(pool[j].ls));
    const n = size(bag);
    if (!SIZES.includes(n)) continue;
    const tiles = flat(bag);
    const poolMask = maskOf(tiles);
    const hits = pool.filter((e) => (e.mask & ~poolMask) === 0n && buildableFrom(e.w, tiles));
    if (hits.length < MIN_WORDS) continue;
    const key = [...tiles].sort().join('|');
    const prev = found.get(key);
    if (!prev || hits.length > prev.words.length) {
      found.set(key, { n, tiles, words: hits.map((h) => h.w) });
    }
  }
}

const bySize = {};
for (const c of found.values()) (bySize[c.n] = bySize[c.n] || []).push(c);

const chosen = [];
for (const n of SIZES) {
  const list = bySize[n] || [];
  const seen = new Set();      // words already reachable from a chosen pool
  const picked = [];

  // Greedy coverage rather than "the richest pools first". Sorting by word
  // count alone picks pools built from the same handful of common letters, so
  // the player meets the same vocabulary over and over. Taking whichever pool
  // adds the most words nobody has seen yet spreads the 837 much wider.
  while (picked.length < PER_SIZE) {
    let best = null;
    let bestNew = 0;
    for (const c of list) {
      if (c.taken) continue;
      let fresh = 0;
      for (const w of c.words) if (!seen.has(w)) fresh++;
      if (fresh > bestNew) { bestNew = fresh; best = c; }
    }
    // Nothing new left to cover: fall back to the richest unused pools so the
    // rotation still has depth.
    if (!best) {
      const filler = list.filter((c) => !c.taken)
        .sort((a, b) => b.words.length - a.words.length)
        .slice(0, PER_SIZE - picked.length);
      for (const c of filler) { c.taken = true; picked.push(c); }
      break;
    }
    best.taken = true;
    picked.push(best);
    for (const w of best.words) seen.add(w);
  }

  chosen.push(...picked);
  console.log(`  ${n} letters: ${picked.length} of ${list.length} pools, covering ${seen.size} words`);
}

// Every word any pool can reach has to travel with the pools.
const needed = new Set(chosen.flatMap((c) => c.words));
const byWord = new Map(targets.map((e) => [e.w, e.en]));
const entries = [...needed].sort().map((w) => `  { w: '${w}', en: ${JSON.stringify(byWord.get(w))} },`);

const out = `/**
 * Generated by tools/genpools.mjs — do not edit by hand.
 *
 * The words levels draw their targets from, and one letter pool for every
 * wheel size. Targets stay in the common end of the dictionary because a
 * target nobody has heard of is a wall, not a puzzle; anything rarer still
 * counts as a bonus find through the full tier-2 list.
 */

export const LEVEL_WORDS = [
${entries.join('\n')}
];

export const POOLS = [
${chosen.map((c) => `  [${c.tiles.map((l) => `'${l}'`).join(', ')}],`).join('\n')}
];
`;

fs.writeFileSync('src/game/levelwords.js', out);
console.log(`\nwrote src/game/levelwords.js — ${chosen.length} pools, ${needed.size} target words`);
